spring:
  application:
    name: SpringBootSecurityDemo
  h2:
    console:
      enabled: true
      path: /h2db
  datasource:
    driver-class-name: org.h2.Driver  
    url: jdbc:h2:mem:testdb
    username: sa
    password: 
    schema:
    - classpath*:liferaysetup.sql
    data:
    - classpath*:liferayinit.sql    
  jpa:
    hibernate:
      ddl-auto: none
server:
  port: 8081
  