CREATE TABLE HOTEL
(HOTEL_ID VARCHAR2(10) PRIMARY KEY,HOTEL_NAME VARCHAR2(50),HOTEL_BOOKING_ID VARCHAR2(10));

CREATE TABLE HOTEL_CUSTOMER
(CUSTOMER_ID VARCHAR2(10),NAME VARCHAR2(50),EMAIL VARCHAR2(50),MOBILE VARCHAR2(10),
CHECK_IN_DATE VARCHAR2(10),CEHCK_OUT_DATE VARCHAR2(10),
HOTEL_CUSTOMER_ID VARCHAR2(10) CONSTRAINT FK_HOTEL_CUSTOMER_ID FOREIGN KEY (HOTEL_CUSTOMER_ID) 
REFERENCES HOTEL(HOTEL_BOOKING_ID));

CREATE TABLE HOTEL_ROOM
(ROOM_ID VARCHAR2(10),NAME VARCHAR2(50),NO_OF_GUESTS VARCHAR2(10),
HOTEL_ROOM_ID VARCHAR2(10) CONSTRAINT FK_HOTEL_ROOM_ID FOREIGN KEY (HOTEL_ROOM_ID) 
REFERENCES HOTEL(HOTEL_BOOKING_ID)); 

